### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by alinex** [alinex/node-builder#1]
In the moment code coverage is only possible on the compiled javascipt. If mocha tests are set to use the coffee sources istanbul can't create any coverage info.

The compiled coverage is not 100% accurately and to support coffee it has to be build into istanbul. Isue opened there. https://github.com/gotwarlost/istanbul/pull/167

**Comment by Albert-IV** [comment]
You might try using [CoffeeCoverage](https://github.com/benbria/coffee-coverage) to instrument your CoffeeScript files, however I'm not sure if that coverage will be 100% accurate.  [Small example.](https://github.com/droppedonjapan/coffeescript-code-coverage)

I really need to double-check its accuracy, just never got around to it.

**Comment by alinex** [comment]
Thanks for your idea, I checked it the last weeks and got it working. Now it is seemless integrated into my development procedure and works just fine.  [CoffeeCoverage](https://github.com/benbria/coffee-coverage) realy does the trick and makes [Istanbul](https://github.com/gotwarlost/istanbul) create the reports as it should.
